### ISSUE TITLE
[Bug] Cannot download files

### ISSUE THREAD

**Issue by GooseGooseDuck198** [UseInterstellar/Interstellar#540]
**Describe the bug**
When I try to download a file from itch.io when using this proxy, I get an error.
It says 'download failed - the server could not find the file.'

I cannot figure out why or how to fix it.

**To Reproduce**

1. Use proxy hosted on koyeb
2. Go to https://13leagues.itch.io/superstition (the game i'm attempting to download a file from
3. start the project
4. Press saves
5. Press save to disc
6. See error in notification about the download

**Expected behavior**
I should be able to download the file.

**Screenshots**
![image](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/80d452b0-c40f-4f1a-9c68-e32db7538a15)
![image](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/4b2ad7b5-73ba-49ae-adb5-3527a09fc040)

**Device Information (please complete the following information):**

- Device: Chromebook
- OS: ChromeOS
- Browser: Google Chrome

**Additional context**

**Comment by MadjikDotPng** [comment]
Ive had this happen to me at one point, I remember finding a fix however yet I can't remember how to reproduce it.

**Comment by GooseGooseDuck198** [comment]
That is disappointing:
I need to export that save file in order to keep my progress for the sequel.

**Comment by MadjikDotPng** [comment]
Would copying the download link then visiting it on its own work?

**Comment by GooseGooseDuck198** [comment]
I don't think it is a download link, it Is just downloading data already in browser cashe

**Comment by MadjikDotPng** [comment]
I don't know if we officially support that feature then, I'll get back to you if I find a workaround.

**Comment by GooseGooseDuck198** [comment]
I will do a screen recording so you can see what I mean...
The data is saved temporarily in browser cache, so if I reload the tab I can keep the saved data.
[Screen recording 2024-03-13 4.11.15 PM.webm](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/c2c1aefb-46b8-4df9-8cb7-7f0dbd564009)

**Comment by GooseGooseDuck198** [comment]
If the feature isn't officially supported, could the ability to download cached files be added?
I found the file I need in local storage:
![image](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/5fcafe96-92eb-48d8-a5ca-e910ba656d66)
(third from the top, one above black bar)

**Comment by bruhwhyamisobad** [comment]
> That is disappointing:
> 
> I need to export that save file in order to keep my progress for the sequel.

Proxies just don't support downloading files 🤷

**Comment by GooseGooseDuck198** [comment]
But i've been able to do it before! 
This issue is something with the new updates, because it used to work.

**Comment by MadjikDotPng** [comment]
This is true.

**Comment by xbubbo** [comment]
I will look into this when I get a chance

**Comment by GooseGooseDuck198** [comment]
Thank you @xbubbo

**Comment by madeline-yana** [comment]
I think this is a bug with Ultraviolet -- I'm trying to download the latest Firefox installer -- it keeps failing around the 40MB mark.

**Comment by Notplayingallday383** [comment]
everyone else is correct. Proxies do not support downloading *most* files. Some files that can be downloaded are usually simple files such as text or image files but for the most part all other files will just download courupted or just not download

**Comment by IncognitoTGT** [comment]
stale/non IN issue, closing
