### ISSUE TITLE
Now.GG Issues

### ISSUE THREAD

**Issue by xbubbo** [UseInterstellar/Interstellar#552]
Reminder for me to fix this later today

**Comment by thrillhoouse** [comment]
reminding

**Comment by xbubbo** [comment]
> Reminder for me to fix this later today

I'll try to do it today, I was busy yesterday

**Comment by skyy-codes** [comment]
> > Reminder for me to fix this later today
> 
> I'll try to do it today, I was busy yesterday

(reminder: its been a day since this comment. still patiently waiting on the fix)

**Comment by xbubbo** [comment]
> > > Reminder for me to fix this later today
> > 
> > 
> > I'll try to do it today, I was busy yesterday
> 
> (reminder: its been a day since this comment. still patiently waiting on the fix)

Unsafe proxy block has now been fixed.

**Comment by skyy-codes** [comment]
> > > > Reminder for me to fix this later today
> > > 
> > > 
> > > I'll try to do it today, I was busy yesterday
> > 
> > 
> > (reminder: its been a day since this comment. still patiently waiting on the fix)
> 
> Unsafe proxy block has now been fixed.

Ok thanks let me know when the alignment stuff is all good

**Comment by skyy-codes** [comment]
> reminder to close this issue

he didnt say alignment was fixed though

**Comment by xbubbo** [comment]
Alignment seems to be working fine without me making any changes, if this issue happens again in the future I will re-open this issue and implement a fix.

**Comment by xbubbo** [comment]
User reported that alignment is bugged again.
![image](https://github.com/InterstellarNetwork/Interstellar/assets/85169821/3a6f3701-042f-49d4-b913-f8e99d789830)

**Comment by xbubbo** [comment]
Allignment fix soon

**Comment by pretzer25** [comment]
> Allignment fix soon

the now gg fix doesnt work

**Comment by skyy-codes** [comment]
> > Allignment fix soon
> 
> the now gg fix doesnt work

it does, its just rather slow :/

**Comment by pretzer25** [comment]
> > > Allignment fix soon
> > 
> > 
> > the now gg fix doesnt work
> 
> it does, its just rather slow :/

well does it take longer than like 15 minutes, IVE TRIED EVERYthING!

**Comment by skyy-codes** [comment]
for me it takes 1-2 minutes as stated so maybe just a skill issue lol

**Comment by skyy-codes** [comment]
issue- the nowGG fix only works if you manually type the nowgg url in/go to
websitesball.com etc, for some reason it doesnt detect it when i directly
launch from games

**Comment by pretzer25** [comment]
[https://github.com/InterstellarNetwork/Interstellar/issues/594](url) would fix the above problem

**Comment by skyy-codes** [comment]
> [this issue](https://github.com/InterstellarNetwork/Interstellar/issues/594) would fix the above problem

Thanks.

Also the bypass is pretty useless cause it doesn’t even activate at all so i have to manually refresh the page myself :/

**Comment by skyy-codes** [comment]
ohh ok

**Comment by skyy-codes** [comment]
Ok, thanks.

**Comment by thecumbine** [comment]
now.gg does sometimes not give me a proxy/vpn error but it is rather inconsistent

**Comment by Xxqzac** [comment]
Bro it still give me tha dumb vpn or proxys like bro ofc we gon be on one please fix

**Comment by IncognitoTGT** [comment]
smartest interstellar user:

**Comment by Xxqzac** [comment]
bro tf u mean i been using interstellar for over a year and it sometimes work and sometimes doesnt how about u fix it dumb ass

**Comment by Xxqzac** [comment]
and fix it so we can get on now.gg

**Comment by thecumbine** [comment]
by the looks of this now.gg is still not working?

**Comment by reherio** [comment]
it just says proxy detected sooooo yeah

**Comment by reherio** [comment]
interstellar the goat but like come on I want to play roblox

**Comment by Xxqzac** [comment]
i swear bro like please fix

**Comment by coolboy123e** [comment]
bruh you don't even need to play Roblox its free on every device why play it at school

**Comment by reherio** [comment]
this is the only device I have

**Comment by skyy-codes** [comment]
@xbubbo I beg you, please add the Now.GG fix back. Now.GG or NowGG.me is not working :(

**Comment by skyy-codes** [comment]
> bruh you don't even need to play Roblox its free on every device why play it at school

Not like everyone has a personal device

**Comment by reherio** [comment]
yeah

**Comment by Xxqzac** [comment]
Please fix day 1 of asking

**Comment by Xxqzac** [comment]
please fix day 2

**Comment by WatchGamingVideos** [comment]
> please fix day 2

holy god damn youtube comment section

**Comment by ProGamer2025** [comment]
the screen keeps getting cut in half, and nothing seems to fix it.

**Comment by Xxqzac** [comment]
day 3 of asking

**Comment by IncognitoTGT** [comment]
be patient. We are not obligated by anything to listen to you. If you keep bothering people, you will be blocked from the repo. 

now.gg did something on THEIR side to block proxies. 

\- @IncognitoTGT

**Comment by Notplayingallday383** [comment]
how about you calm down buddy. Simply be patient we are handling this

**Comment by ProGamer2025** [comment]
Sorry, I just thought it was an interstellar issue.

**Comment by yu6x** [comment]
> day 3 of asking

roblox is not important in school dawg. if you really need a fix why wont you make one and do a pr?

**Comment by proudparrot2** [comment]
> day 3 of asking

hey there, please be patient with us as bubbo is trying his best to get it working. he also has school and other things to take care of outside of Interstellar business, and the best thing to do right now is wait until we can come up with a fix. thank you!

**Comment by uhidontkno** [comment]
smartest interstellar users

**Comment by uhidontkno** [comment]
chat i think yall need this
![image](https://github.com/UseInterstellar/Interstellar/assets/86028086/c2d39562-0a34-42e5-9a58-c0c76d31d55e)

**Comment by uhidontkno** [comment]
actually yall dont because interstellar is full of brainrot in the first place, yall just shut the fuck up now.gg is on their happy way to block proxies again

**Comment by uhidontkno** [comment]
time to go to the verizon store and make one of the demo phones a vpn

**Comment by uhidontkno** [comment]
> interstellar administrator here,
> 
> can you guys actually stop bothering us about how much you want to play roblox every single day it's kinda annoying clearing out my github notifications!! it'll be fixed whenever bubbo/dev team decides to do so!!!!!!! they have lives too!!!!!!!!!!
> 
> thanks for using interstellar and have a great day!

average interstellar user

**Comment by Xxqzac** [comment]
bro its not i just wanna play roblox i love interstellar but at the same time come on man like please atleast have it say not working i been trying everyday

**Comment by IncognitoTGT** [comment]
be patient

 # ROBLOX NOT WORKING IS NOT UNDER OUR CONTROL

**Comment by reherio** [comment]
for some reason it was working for me but then the next day it didnt
it was weird

**Comment by skyy-codes** [comment]
it technically is, bubbo added a working fix then removed it for some
reason :(

**Comment by uhidontkno** [comment]
> bro its not i just wanna play roblox i love interstellar but at the same time come on man like please atleast have it say not working i been trying everyday

have some patience :skull:

**Comment by uhidontkno** [comment]
or uh idk dont be addicted to roblox

**Comment by reherio** [comment]
nah cause bro fixed it but then removed the fix because like 5 days ago It was working but the day after that it didn't like tf??

**Comment by uhidontkno** [comment]
> nah cause bro fixed it but then removed the fix because like 5 days ago It was working but the day after that it didn't like tf??

shut the ever living fuck up

**Comment by uhidontkno** [comment]
i swear these interstellar skids

**Comment by reherio** [comment]
> > nah cause bro fixed it but then removed the fix because like 5 days ago It was working but the day after that it didn't like tf??
> 
> shut the ever living fuck up

I get what u mean I'm just confused on why he added a fix then took it away

**Comment by IncognitoTGT** [comment]
it was an unreliable fix

**Comment by reherio** [comment]
oh ok thank u

**Comment by uhidontkno** [comment]
duh

**Comment by yosoof3** [comment]
> chat i think yall need this ![image](https://private-user-images.githubusercontent.com/86028086/332960202-c2d39562-0a34-42e5-9a58-c0c76d31d55e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDAzNzUsIm5iZiI6MTcxNjc0MDA3NSwicGF0aCI6Ii84NjAyODA4Ni8zMzI5NjAyMDItYzJkMzk1NjItMGEzNC00MmU1LTlhNTgtYzBjNzZkMzFkNTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE2MTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NDg2YTE2YTIyMDI0MjY3MTg2Yjk0NzUzOGMxM2NhYzlkMDE2NGNkMDdmNTlkOTkyNDY5ODQzZDc0NDc1MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6PMtC6or7v0u5qGpu_u5wPdZFrd-V6SaKsrRe4TuuY)

imagine using deblok.. shoulda used stardust

**Comment by uhidontkno** [comment]
stfu

**Comment by yosoof3** [comment]
> stfu
bros mad he got banned off spaceness :middle_finger:

**Comment by IncognitoTGT** [comment]
Locked this for now as this issue has descended into a yap session, will be unlocked when something new occurs
