### ISSUE TITLE
I have no idea what happened, but it is a huge issue !!EPILEPSY WARNING!! [Bug] 

### ISSUE THREAD

**Issue by GooseGooseDuck198** [UseInterstellar/Interstellar#568]
**Describe the bug**
Reddit == Epilepsy Warning

So I tried to access Reddit on the proxy, as any normal, mentally stable person would, when (as always), Reddit said "nope!" 
![Screenshot 2024-03-24 7 23 36 PM](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/8cb4cba9-eae3-46dc-9971-252afee940c5)

So I clicked on the link to log into my account, when Reddit had a stroke. (I'm not pressing anything except trying to open the console)
!!!EPILEPSY WARNING!!! VIDEO MAY BE HARMFUL TO PHOTOSENSITIVE VIEWERS!!! PLEASE DON'T DIE OR SUE ME!!!
[Screen recording 2024-03-24 7.18.16 PM.webm](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/421ff565-975c-4858-ac24-58ead342ad4c)

Here is a screenshot of the console:
![image](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/9db3a5f4-5528-4372-a167-9182e1afbc42)

Also y'all, please don't steal my instance link, It cant support any more people...
I only left it unblurred because I can't be bothered to draw over the video frame by frame and hiding the link in the screenshot won't stop anyone from slowing down the video.

**To Reproduce**

1. Go to the proxy (hosted on koyeb)
2. Go to reddit.com
3. Attempt to sign into account

**Expected behavior**
I should be able to sign in without having a seizure

**Device Information (please complete the following information):**

- Device: Chromebook
- OS: ChromeOS
- Browser: Google Chrome

**Additional context**
Yes I use reddit ironically don't judge me or i'll steal your soul.

**Comment by yet66** [comment]
This can't be fixed reddit blocks anyone who accesses the website on a proxy

**Comment by IncognitoTGT** [comment]
Logging in will let you use reddit. Reddit bans certain non logged in IPs

**Comment by GooseGooseDuck198** [comment]
@yet66 @IncognitoTGT 

Did you read the rest of the post? I went over that.

The issue is that I can't sign in because the page is looping.

**Comment by yet66** [comment]
> @yet66 @IncognitoTGT
> 
> Did you read the rest of the post? I went over that.
> 
> The issue is that I can't sign in because the page is looping.

The sign in page will not work because reddit blocks anyone who is accessing the website through a proxy

**Comment by FatGrizzly** [comment]
> > @yet66 @IncognitoTGT
> > Did you read the rest of the post? I went over that.
> > The issue is that I can't sign in because the page is looping.
> 
> The sign in page will not work because reddit blocks anyone who is accessing the website through a proxy

No?

I can login to my reddit account via a vpn/proxy and use it normally.

**Comment by IncognitoTGT** [comment]
Ultraviolet issue that I'm seeing on other proxies too, nothing to do with Interstellar.
