### ISSUE TITLE
Cyclic No Longer Working [Bug] 

### ISSUE THREAD

**Issue by TornadoRoad46** [UseInterstellar/Interstellar#573]
Cyclic will no longer deploy as it violates their terms of use, I saw it coming. Looks like Cyclics bot or whatever read through the package.json and flagged line 2 as a violation, changing it does nothing either. Anyways, it seems to be deemed a loss, or am I missing something.

**Comment by IncognitoTGT** [comment]
they shut down

**Comment by WatchGamingVideos** [comment]
Cyclic shut down this is the second time I am saying that wtf

**Comment by IncognitoTGT** [comment]
resolved
