### ISSUE TITLE
Apps to add (I know you just added some but here are more good ones)

### ISSUE THREAD

**Issue by interstellarforker** [UseInterstellar/Interstellar#629]
MUT.GG
Wordle
123Movies
Reddit 
MLB
NFL
NBA
CrazyGames
Onefootball

Thats about it

**Comment by Harlan124** [comment]
@xbubbo now.gg still down

**Comment by IncognitoTGT** [comment]
are these added?

this is a stale issue and will be closed within 1 week if there's no response

**Comment by WatchGamingVideos** [comment]
> are these added?
> 
> this is a stale issue and will be closed within 1 week if there's no response

I added most of these to my fork

**Comment by WatchGamingVideos** [comment]
bubbo said he'd add on APRIL 20

It's been a but no

**Comment by WatchGamingVideos** [comment]
I dont have them all. Bro u can steal my apps list rn its ok I have like 50+ new apps lol

**Comment by WatchGamingVideos** [comment]
I don't wanna spam PR's so if my "Fancade" PR isn't closed or merged I'll wait

**Comment by IncognitoTGT** [comment]
@WatchGamingVideos put ALL apps on the same pr

**Comment by WatchGamingVideos** [comment]
> @WatchGamingVideos put ALL apps on the same pr

Aight I'll do it later becaue I have class rn.
Not to sound like a beggar but since I cannot speak to the discord mods anymore can you while I have class? Ty and I'll do it in like an hour or so

**Comment by IncognitoTGT** [comment]
stale
