### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by As90909w** [UseInterstellar/Interstellar#636]
![image](https://github.com/UseInterstellar/Interstellar/assets/163041654/f41e6598-6f12-442d-9c4d-3c207eba333d)

So this happens...and now.gg is not working. I mean it IS working, but, well the window is not fitting. Please email me at the email: [p1480132@outlook.com          [p1480132@outlook.com](url)

I have contributed to Google Flutter.

**Comment by As90909w** [comment]
PLEASE HELP

**Comment by Harlan124** [comment]
@As90909w oh i know how to fix

**Comment by 588735** [comment]
@Harlan124 how?

**Comment by As90909w** [comment]
pls someone help me

**Comment by As90909w** [comment]
PLSSSSS
