### ISSUE TITLE
CAN YOU SHUT UP @As90909w

### ISSUE THREAD

**Issue by As90909w** [UseInterstellar/Interstellar#644]
CAN YOU SHUT UP @As90909w

_Originally posted by @IncognitoTGT in https://github.com/UseInterstellar/Interstellar/issues/642#issuecomment-2075589405_

**Comment by As90909w** [comment]
We should do something about   @IncognitoTGT

**Comment by IncognitoTGT** [comment]
join https://discord.gg/interstellar

**Comment by As90909w** [comment]
Yeah join that discord

**Comment by IncognitoTGT** [comment]
well then what's your username?
