### ISSUE TITLE
[Bug]  Pokemon Showdown Proxy Detection

### ISSUE THREAD

**Issue by pretzer25** [UseInterstellar/Interstellar#668]
yes

**Comment by pretzer25** [comment]
Just wait lie 4 minutes you will be disconnected, if it loads then it will tell you that you are on a proxy

**Comment by juniorbutyeah** [comment]
there's nothing we can do about this

**Comment by pretzer25** [comment]
You solved the now gg bypass

**Comment by IncognitoTGT** [comment]
stale, also not something directly under our control as it's the IP address of the proxy
