### ISSUE TITLE
[Game]

### ISSUE THREAD

**Issue by thecumbine** [UseInterstellar/Interstellar#673]
**What is the name of the game?**
Half-life

**What is the link to the game?**
https://pixelsuft.github.io/hl/xash.html#150

**What is the category of the game? [Optional]**
FPS
**Quick Note**
This URL contains the full story mode of Half-Life.
unlike the current URL the just has the demos of HL.

**Comment by replitidk** [comment]
you know what this game request is unsurprising due to your name

**Comment by replitidk** [comment]
you know i tried this link it works pretty well its good this would be nice to have in the games part of interstellar

**Comment by IncognitoTGT** [comment]
stale
