### ISSUE TITLE
discord crashes interstellar when I try to go into server or dm[Bug] 

### ISSUE THREAD

**Issue by jdem0637** [UseInterstellar/Interstellar#694]
discord crashes interstellar
**To Reproduce**

1. Go to 'intestellar'
2. Click on 'apps'
3. Scroll down to 'discord'
4. log in to discord
5. go to a server
6. see that it stops working

**Expected behavior**
go to dm or server then it stays working
**Screenshots**

**Device Information (please complete the following information):**

- Device:Chromebook
- OS ChromeOS
- Browser Chrome

**Additional context**

> [!IMPORTANT]
> Do not post your personal information here this includes but is not limited to email addresses, names, and age.

**Comment by WatchGamingVideos** [comment]
discord doesnt load for me lol how'd u get it to load

**Comment by madeline-yana** [comment]
going through the apps section seems to work for me, though i dont know if i can login or not as it just sent me to the main landing page (e.g. index.html, i think)

**Comment by IncognitoTGT** [comment]
Can you send a screen recording of the issue?

**Comment by madeline-yana** [comment]
it works again after redeploying

**Comment by madeline-yana** [comment]
doesnt matter much, but basically
the site itself wont work even though the tab name iwll
will also sometimes throw a networkerror

**Comment by madeline-yana** [comment]
probably either a koyeb issue or a me issue, not a big deal

**Comment by IncognitoTGT** [comment]
Yeah
