### ISSUE TITLE
[Bug] Recommended to deprecate the Google Gemini app from Interstellar

### ISSUE THREAD

**Issue by TheW0NK** [UseInterstellar/Interstellar#702]
**Description**
Google will not sign in due to the possibilities for it being an insecure browser.

**To Reproduce**

1. Go to the Gemini app
2. Click on sign in
3. Attempt to sign in

**Expected behavior**
It should say "Couldnt sign you in. this browser or app may not be secure."

**Screenshots**

**Device Information (please complete the following information):**

- Device: Windows Lenovo touchscreen
- OS Windows
- Browser Chrome

> [!IMPORTANT]
> Do not post your personal information here this includes but is not limited to email addresses, names, and age.

**Comment by S-PScripts** [comment]
> no point removing it just make it red

why would you make it red if it will **never** work again?

**Comment by IncognitoTGT** [comment]
Ultraviolet issue that's on other proxies too, nothing to do with Interstellar.

@xbubbo deprecate all apps that req a google login
