### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by reherio** [UseInterstellar/Interstellar#707]
Netflix

(https://www.netflix.com/)

 its an app and i was wondering if you could put it if not thats fine i just really wanted it

**Comment by ProgrammerIn-wonderland** [comment]
I would advise against this, (disclosure: I am from TN) Netflix has tried to ensue legal actions on web proxies that access Netflix before

**Comment by reherio** [comment]
nvm

**Comment by uhidontkno** [comment]
bro doesnt know how to go to netflix.com on interstellar proxy
