### ISSUE TITLE
[Bug]  Error: Headers

### ISSUE THREAD

**Issue by 5kh0** [UseInterstellar/Interstellar#720]
**Describe the bug**
When playing some games, it gives an error about headers:

Error
The following features required to run Godot projects on the Web are missing:
Cross Origin Isolation - Check web server configuration (send correct headers)
SharedArrayBuffer - Check web server configuration (send correct headers)

**To Reproduce**

1. Go to Games
2. Click on Buckshot Roulette
3. See error

**Expected behavior**
Ability to play Buckshot Roulette

**Screenshots**
![image](https://github.com/UseInterstellar/Interstellar/assets/148277487/2ebc7a67-5b6a-4377-886a-d363de55b923)

**Device Information (please complete the following information):**

- Device: Chromebook
- OS Chrome OS
- Browser Chrome

**Additional context**

I am on Github Codespaces
This happens for multiple games and websites

**Comment by IncognitoTGT** [comment]
Yeah this seems like an application ssue and not for IN
