### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by goosehoonk** [UseInterstellar/Interstellar#721]
Ok i'm going to keep this brief.

Firstly, why did you remove the ability to disable ads? My AdBlocker doesn't work on this site, and taking away the ability to remove ads is just a jerk move. 
On the topic of ads, pick better hosts. Almost all of the ads on this site are malvertising and phishing scams. This is a serious risk and needs to be fixed immediately.

Also, every time I open the apps tab, a new tab is opened hosting a McAfee malvertising virus page. If I wasn't running a sandboxed web browser I would have gotten infected by this. You need to fix this issue, and pick better advertising providers.

**Comment by IncognitoTGT** [comment]
1.  do you have eyes?
![Screenshot 2024-05-28 at 21 31 17](https://github.com/UseInterstellar/Interstellar/assets/72108630/ae69a586-9eb0-45a3-9c08-fd271c3e2a03)
2. just turn it off lmao, iirc there aren't that many ad services that would do something with a proxy
3. Make sure to click the X at the very top right. Also, chromebooks can't run the McAfee scams since it's a chromebook, and your blocker probably blocks the sus pages anyways. 

hope this helps :)

**Comment by goosehoonk** [comment]
I am hosting my own server. The problem is I can't remove ads on my own server.
![image](https://github.com/UseInterstellar/Interstellar/assets/168311677/de7e3b34-cdbb-4595-a76c-8f0cf730c96f)

**Comment by goosehoonk** [comment]
How do I do that? I was under the impression it updated automatically

**Comment by IncognitoTGT** [comment]
run 
```
git pull --force --allow-unrelated-histories
```
where the repo is located

**Comment by GooseGooseDuck198** [comment]
now it's just teasing me
![image](https://github.com/UseInterstellar/Interstellar/assets/119032101/3450f843-652a-49a5-8f85-e04f86fa322f)

**Comment by goosehoonk** [comment]
I'm redeploying again rn, lemme see if this fixes it.

**Comment by goosehoonk** [comment]
It is still greyed out.

**Comment by goosehoonk** [comment]
Wait I found it

**Comment by GooseGooseDuck198** [comment]
![image](https://github.com/UseInterstellar/Interstellar/assets/119032101/fda87b73-5baf-4bb5-87b0-d9ae7a5db51e)
Also I just realized im using two different github accounts for this XD
This one is on a windows laptop, the other is a chromebook.

**Comment by goosehoonk** [comment]
Ok I fixed it by removing that disabled="" tag.
