### ISSUE TITLE
Re-Open now.gg issues thread

### ISSUE THREAD

**Issue by WatchGamingVideos** [UseInterstellar/Interstellar#724]
I wanna ask how to QUICKLY bypass now.gg unsafe proxy detected crap

Like in less that 5 min because it usually takes me forever

**Comment by WatchGamingVideos** [comment]
Wait hold on

Bring back that fix from a few months ago if it still works.

Because frame.js doesn't exist anymore and I wanted to add the fix to my fork but it gone

**Comment by IncognitoTGT** [comment]
this is the 2nd  issue/discussion you made regarding this. 

you WILL be blocked from the repo if you can't be patient
