### ISSUE TITLE
[Feature] Custom Themes Support

### ISSUE THREAD

**Issue by goosehoonk** [UseInterstellar/Interstellar#733]
The current themes are great, but I would like more customization to the proxy. I noticed on the checklist this was upcoming, so I would like to propose a way this could work.

I think a good way to do this would be using a JSON file to choose colours for the theme, so you could create a new theme by modifying values in a template JSON file. For example if I wanted to make it blue-er, I could go through a JSON file, looking for the sections I wanted to change, and modify the RGB (or HEX, or HSV) values to achieve the preferred colours.

This could also be done by adding a tab for customization, where you could select a feature, and a colour picker would appear, allowing us to change that features colours. This could be saved in an array, and saved in browsers cache. 

If you'd like, I can make a bare-bones version to show you what I mean. I think this would be a positive change to the proxy, and would break the monotony of coffee themed themes.

**Comment by IncognitoTGT** [comment]
We already have css variables which are customized by every theme. When I was making the Catppuccin themes, I just used that set of css variables, so we already have that. 

And for the custom themes im probably gonna have the css stylesheet stored in localstorage as base64 and then have it as a `<link>` tag that points to that data URI

**Comment by goosehoonk** [comment]
That would probably be easier for the less technically minded to understand, whereas mine is convoluted and confusing for even myself. I was looking through the themes code and found them slightly confusing, but I only have a basic knowledge of CSS due to my short time making web applications. 

I think combining the ideas (the latter idea, the colour picker tab) would be beneficial. Then we (the user) could pick colours via a popup colour selector, and it would save to said CSS stylesheet. Do you think that would work in the scope of this project?

**Comment by IncognitoTGT** [comment]
Interstellar codebase is a nightmare so yeah it's confusing

v6 is likely gonna be a complete rewrite
