### ISSUE TITLE
what's going on? it says an unexpected issue has acured 

### ISSUE THREAD

**Issue by Thundergamer579** [UseInterstellar/Interstellar#737]
![Screenshot 2024-05-31 1 11 34 PM](https://github.com/UseInterstellar/Interstellar/assets/171292586/f8e787fc-4dc4-46d6-b403-678c4c630974)

**Comment by IncognitoTGT** [comment]
Try refreshing the page, or making a new codespace if the issue's still there.

Also, GitHub issues is NOT the place to report non code-related issues you're having, that belongs in discussions or the discord.
