### ISSUE TITLE
[Bug] Unable to open Discord 

### ISSUE THREAD

**Issue by madeline-yana** [UseInterstellar/Interstellar#741]
**Describe the bug**
Discord will not load past landing page.

**To Reproduce**

1. Go to site
2. Click on search bar
3. Enter either "https://discord.com/app" or "https://discord.com/login"
4. Site will buffer endlessly, or throw a 404 error after some time

**Expected behavior**
Discord loads and can use.

**Screenshots**
Unable to send screenshot

**Device Information (please complete the following information):**

Lenovo ThinkPad T460p
OS: Windows 10 (22h2)
Browser: Firefox 126.0

**Additional context**
This is a very spontaneous issue, in the past redeploying would fix all of this. This has stopped working though

**Comment by madeline-yana** [comment]
Other sites will work perfectly fine

**Comment by IncognitoTGT** [comment]
Where are you hosting the Interstellar link?

**Comment by madeline-yana** [comment]
Through Koyeb

https://forward-honoria-yana.koyeb.app

**Comment by madeline-yana** [comment]
Using the Apps link and the Join link (on the 404 page) throw the same error

**Comment by IncognitoTGT** [comment]
Seems like a device issue as I just logged into discord onto there. Try clearing cache

**Comment by madeline-yana** [comment]
Not sure how or why it would be my device... Especially if it's such a spontaneous issue.

**Comment by madeline-yana** [comment]
For the record, this started as I upgraded to 5.2.0

**Comment by IncognitoTGT** [comment]
Try clearing cache

**Comment by madeline-yana** [comment]
I just did

**Comment by IncognitoTGT** [comment]
Are you having the issue in other devices?

**Comment by madeline-yana** [comment]
I have no other devices to test with.

**Comment by IncognitoTGT** [comment]
It seems like a device issue as I don't get the issue on my end, thus it is not a bug with IN.
