### ISSUE TITLE
[Bug] My interstellar won't work

### ISSUE THREAD

**Issue by TTVPhyllis** [UseInterstellar/Interstellar#754]
So like I woke up this morning finna hop on the games section all of a sudden it says "Connection timed out" are ya'll working on the servers?
![Screenshot 2024-06-04 1 39 57 PM](https://github.com/UseInterstellar/Interstellar/assets/153538968/7a9abed4-7277-4458-ae5b-bce390ccca68)
device: Chrome OS

**Comment by IncognitoTGT** [comment]
Interstellar is currently down.

Check the [Discord](https://discord.gg/interstellar) for updates.
