### ISSUE TITLE
Unsafe Proxy

### ISSUE THREAD

**Issue by Yashneel123** [UseInterstellar/Interstellar#767]
**Describe the bug**
The proxy is saying  that it is unsafe and it is not letting me play

**To Reproduce**
Steps to reproduce the behavior

1. Go to  Genshin Impact or Roblox
2. Click 1 time
3. Wait

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

- Device: School Chromebook
- OS : Chrome OS
- Browser: Chrome

**Additional context**

> [!IMPORTANT]
> Do not post your personal information here this includes but is not limited to email addresses, names, and age.

**Comment by IncognitoTGT** [comment]
Now.gg is broken on Interstellar. Follow #552 for updates

**Comment by Yashneel123** [comment]
Ok
