### ISSUE TITLE
now.gg bug fix ideas

### ISSUE THREAD

**Issue by As90909wwu** [UseInterstellar/Interstellar#777]
now. gg is not working again, school proxy - DHPD proxy is blocking the network for attempting to enter - here is the network log report from chrome

![image](https://github.com/UseInterstellar/Interstellar/assets/171374617/b61fe8c6-a36c-4996-ad1b-e4480988f349)
 So I thought up an idea, why not plugin a batchfile to compute the proxy?

**Comment by As90909wwu** [comment]
My name is Andrew Shin. email me at p1480132@outlook.com if you think of anything!
Or follow me at @As90909

thanksssss
:)  :)

**Comment by As90909wwu** [comment]
Actully this is my now.gg bug proxy repository at the account
follow at @As90909w

**Comment by IncognitoTGT** [comment]
what are you smoking and where do I buy it
