### ISSUE TITLE
npm run start not working

### ISSUE THREAD

**Issue by As90909wwu** [UseInterstellar/Interstellar#780]
so i typed in the     npm run start and it didn't work. I have also tried the following:

pnpm run start
npm I && npm run start
npm I
and more

**Comment by uhidontkno** [comment]
have you tried installing node.js :exploding_head:

**Comment by Notplayingallday383** [comment]
can someone close this bruh. have you considered installing node...

**Comment by As90909wwu** [comment]
yes node.js dosent work  :(

**Comment by IncognitoTGT** [comment]
Can you shut up

**Comment by IncognitoTGT** [comment]
@As90909wwu also join IN discord and tell me your discord username
