### ISSUE TITLE
vercel [Bug] 

### ISSUE THREAD

**Issue by giggity-joe** [UseInterstellar/Interstellar#782]
I was trying to deploy interstellar repo in vercel until this message pops up said "this serverless function has crashed"
![Screenshot 2024-06-12 11 06 05 AM](https://github.com/UseInterstellar/Interstellar/assets/156235723/d256bdb9-dbcc-412b-b069-fc2476e8aac6)

**Comment by IncognitoTGT** [comment]
Interstellar is broken on vercel
