### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TTVPhyllis** [UseInterstellar/Interstellar#798]
Hey so are the servers down or something they've been down for a day

Chrome OS
![Screenshot 2024-07-05 4 58 50 PM](https://github.com/UseInterstellar/Interstellar/assets/153538968/ae46e37b-7c6a-4b7c-83d8-fe455e78e7f0)

**Comment by IncognitoTGT** [comment]
IN is down, join discord.gg/interstellar and check https://status.gointerstellar.app

**Comment by TTVPhyllis** [comment]
how long will it be down for and sorry for the late reply
