### ISSUE TITLE
how long will gointerstellar be down?

### ISSUE THREAD

**Issue by TTVPhyllis** [UseInterstellar/Interstellar#800]
so its been a LONG time since gointerstellar been up how long will it be till its back up on
![Screenshot 2024-07-09 7 42 50 PM](https://github.com/UseInterstellar/Interstellar/assets/153538968/657529b5-75bf-4d9c-b763-23e84b3d9373)
ChromeOS

**Comment by IncognitoTGT** [comment]
Check the [status page](https://status.gointerstellar.app) and the [discord](https://discord.gg/interstellar) for more
