### ISSUE TITLE
No more subway surfers

### ISSUE THREAD

**Issue by uruser-sourse** [UseInterstellar/Interstellar#805]
Subway surfers doesn't exist anymore 

1. Go to games tab
2. Click on games tab
3. Scroll down to subway surfers
4. Click on subway surfers 

**Expected behavior**
Be able to play subway surfers

**Unexpected behavior**
Page not found 

- Device: Chromebook 
- OS: ChromeOS
- Browser: Chrome

**Comment by IncognitoTGT** [comment]
This will be fixed in v6.
