### ISSUE TITLE
error creating new instance

### ISSUE THREAD

**Issue by Maxdalatexfurry** [UseInterstellar/Interstellar#814]
won't launch on koyeb at all when trying to launch it

Steps to reproduce the behavior: go to koyeb and try to create a new instance and wait

1. Go to 'koyeb'
2. Click on 'create new instance'
3. wait for some of it to build

I expected it to recreate a new instance

device: chromebook, Mac
OS: chromes, macOS
browser: chrome, safari 
[Koyeb.pdf](https://github.com/user-attachments/files/16628427/Koyeb.pdf)

**Comment by IncognitoTGT** [comment]
what error?

**Comment by Maxdalatexfurry** [comment]
[Koyeb.pdf](https://github.com/user-attachments/files/16628388/Koyeb.pdf)
that

**Comment by IncognitoTGT** [comment]
delete the file `pnpm-lock.yml` from your fork and try again

**Comment by Maxdalatexfurry** [comment]
thank you!
