### ISSUE TITLE
[Bug] school blocked the proxy

### ISSUE THREAD

**Issue by TTVPhyllis** [UseInterstellar/Interstellar#815]
So I was finna use the proxy and I tried to get on discord and it got blocked cause my school use Blocksi

Chrome OS
![Screenshot 2024-08-16 7 31 54 PM](https://github.com/user-attachments/assets/b73805b5-77e8-4da7-be6a-5590991ce7ef)

**Comment by IncognitoTGT** [comment]
you made this issue 6 different times bruh
