### ISSUE TITLE
[Bug] it says "RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]."

### ISSUE THREAD

**Issue by GETGOODD** [UseInterstellar/Interstellar#825]
**Describe the bug**

**To Reproduce**
![Screenshot 2024-08-24 5 44 04 AM](https://github.com/user-attachments/assets/896b8fe7-2bbc-4173-9fbf-cef152c81c36)

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

- Device: [Ex. Chromebook, iPad, etc.]
- OS [Ex. ChromeOS, Windows, iOS
- Browser [Ex. Chrome, Safari]

**Additional context**

> [!IMPORTANT]
> Do not post your personal information here this includes but is not limited to email addresses, names, and age.

**Comment by GETGOODD** [comment]
says it on all apps/games

**Comment by IncognitoTGT** [comment]
Did you make the codespace public

**Comment by GETGOODD** [comment]
it works now
