### ISSUE TITLE
[Bug] about://blank Popup cloaking redirects to random sites

### ISSUE THREAD

**Issue by killsecurly** [UseInterstellar/Interstellar#830]
**Describe the bug**
I turned on about://blank tab cloaking, and then when reloaded, it suddenly started redirecting me to sites like Kahoot and Classroom.

**To Reproduce**
Deploy to Koyeb (even though I think this doesn't really change things)
Go to settings
Turn on tab cloaking
Restart

**Expected behavior**
Cloak the tab.

**Screenshots**
[Interstellar Cloak.webm](https://github.com/user-attachments/assets/b4365140-bb76-4881-a56c-2110198d36ce)

**Device Information (please complete the following information):**
Dell Chromebook 3110
Intel Celeron N4500
ChromeOS 124.0.6367.225 (Official Build) (64-bit) 
15823.60.0 (Official Build) stable-channel dedede

**Additional context**
None

**Comment by IncognitoTGT** [comment]
check if the tab is opened somewhere else by clicking ctrl+tab

**Comment by killsecurly** [comment]
@IncognitoTGT

Nope, nothing appears. Maybe Securly disables about://blank sites?

I have Filter and Classroom.

**Comment by IncognitoTGT** [comment]
try going to `https://<your link>/st`

**Comment by killsecurly** [comment]
> try going to `https://<your link>/st`

@IncognitoTGT 

Also redirects. No popups open.

**Comment by SkyeGamesYT** [comment]
Have you allowed "popups and redirects" in your browser settings?

**Comment by killsecurly** [comment]
@SkyeGamesYT 
Yes.

**Comment by IncognitoTGT** [comment]
stale, closing
