### ISSUE TITLE
[Bug] Interstellar Closes after ~30 minutes 

### ISSUE THREAD

**Issue by CoderMonkey1956** [UseInterstellar/Interstellar#831]
**Describe the bug**

Whenever I run "pnpm I && pnpm start" it will start the website, but then it will automatically stop after about 30 minutes. I made sure that my codespaces timeout was 4 hours, so I don't think it's a GitHub Codespaces issue. After 30 minutes, it will give me a 404 error when 1 minute ago it was working fine.

**To Reproduce**

1. Go to the address bar after 30  min
2. Type in your link
3. Click Enter
4. Get a 404 error

**Expected behavior**

The website would stay up for 4 hours as that's what I have my GitHub suspend time set to.

**Device Information (please complete the following information):**

- Device: Chromebook
- OS ChromeOS
- Browser Chrome

**Comment by IncognitoTGT** [comment]
the place where you ran `pnpm start`

**Comment by IncognitoTGT** [comment]
I dont see any issue?

**Comment by IncognitoTGT** [comment]
I can run it on a codespace without an issue

**Comment by IncognitoTGT** [comment]
do you close the codespace tab out?

**Comment by replitidk** [comment]
dude just run it then go to settings and launch about blank and try that I guess if the issue still happens welp idk

**Comment by IncognitoTGT** [comment]
yeah 
keep it open or it'll pause in 30min

**Comment by devgge** [comment]
mines closes even when tab is open

**Comment by CoderMonkey1956** [comment]
> mines closes even when the tab is open

Yes I eventually contacted GitHub support on this and you'll need to refresh the tab or just restart it

**Comment by CoderMonkey1956** [comment]
Also guys to be clear this isn't an issue with interstellar
