### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Maxdalatexfurry** [UseInterstellar/Interstellar#833]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i have to make a new instance whenever securly blocks it

**Describe the solution you'd like**
a way to change the url to avoid detection by securly

**Describe alternatives you've considered**
changing the name manually or deleting the instance and redoing it so it randomizes a name

**Additional context**
it would be like how croxyproxy hides itself with ips

**Comment by IncognitoTGT** [comment]
deleting an instance of what?

**Comment by Maxdalatexfurry** [comment]
> deleting an instance of what?

on koyeb i have to delete the instance its using bc its blocked those keywords

**Comment by killsecurly** [comment]
Password protection might work.

**Comment by Maxdalatexfurry** [comment]
now tell me how i would do that?

**Comment by IncognitoTGT** [comment]
edit config.json

**Comment by Maxdalatexfurry** [comment]
yeah didnt work 
![Screenshot 2024-09-17 1 33 50 PM](https://github.com/user-attachments/assets/0e3a04f6-3c57-4885-9d46-80e60012b89c)

**Comment by replitidk** [comment]
hol up question does it get blocked the second you open it or does it take like 2 minutes then it gets blocked @Maxdalatexfurry

**Comment by Maxdalatexfurry** [comment]
it blocks it when im changing classes and its on a different computer

**Comment by replitidk** [comment]
> it blocks it when im changing classes and its on a different computer

wdm like you close your computer and get onto it again in the next class period then its blocked?

**Comment by Maxdalatexfurry** [comment]
yup

**Comment by Maxdalatexfurry** [comment]
thats exactly how it happens

**Comment by Maxdalatexfurry** [comment]
tho its with a different computer every time

**Comment by replitidk** [comment]
> tho its with a different computer every time

so you have a different computer for every class period???????

**Comment by Maxdalatexfurry** [comment]
yeah its a chromebook cart with like 20 something computers in it

**Comment by Maxdalatexfurry** [comment]
but the thing is i try to use the same chromebook but it blocks it on the same chromebook

**Comment by Maxdalatexfurry** [comment]
i have 7 classes and i try to use the same chromebook number but everytime i do it blocks it

**Comment by replitidk** [comment]
> but the thing is i try to use the same chromebook but it blocks it on the same chromebook

I have had the same issue just open it quickly go to settings and about:blank cloak just make sure you don't leave the main link open with the numbers and stuff open so securely wont get time to search for the keywords and block it

**Comment by replitidk** [comment]
it works for me just about blank cloak and don't leave the main link open so it gets time to block

**Comment by replitidk** [comment]
> so your saying to exit out the site then close the computer

open link about blank make sure main link doesn't stay open even while using it on your first hour one then once second hour rolls around close about blank link go to second hour reopen the main link and about blank rinse and repeat.

**Comment by Maxdalatexfurry** [comment]
thats what i want to try to avoid...

**Comment by killsecurly** [comment]
> > thats what i want to try to avoid...
> 
> well idk then man so then in your case you would need a URL changer like you suggested

Try hosting it at home, using one ridiculously long domain and since subdomains are unlimited, just make one every time.

**Comment by IncognitoTGT** [comment]
stale, closing
