### ISSUE TITLE
3 failing, 4 successful, and 1 skipped checks  pages build and deployment / build (dynamic) Failing after 16s Details  SonarCloud Code Analysis Failing after 44s - Quality Gate failed Details  Vercel - Account is blocked. Details  CodeQL / Analyze (javascript-typescript) (dynamic) Successful in 3m Details  Remove Ads / update-Ad-Free (push) Successful in 28s Details  pages build and deployment / report-build-status (dynamic) Successful in 9s Details  pages build and deployment / deploy (dynamic) Skipped Details  Cloudflare Pages - Deployed successfully

### ISSUE THREAD

**Issue by Kason23** [UseInterstellar/Interstellar#840]
3 failing, 4 successful, and 1 skipped checks

pages build and deployment / build (dynamic) Failing after 16s
[Details](https://github.com/UseInterstellar/Interstellar/actions/runs/10783792118/job/29906332606)

SonarCloud Code Analysis Failing after 44s - Quality Gate failed
[Details](https://github.com/UseInterstellar/Interstellar/runs/29906370354)

Vercel - Account is blocked.
[Details](https://vercel.com/knowledge/why-is-my-account-deployment-blocked)

CodeQL / Analyze (javascript-typescript) (dynamic) Successful in 3m
[Details](https://github.com/UseInterstellar/Interstellar/actions/runs/10783792208/job/29906332930)

![image](https://github.com/user-attachments/assets/6385bb33-98b0-468e-a26c-b3ab0bcb4b5d)

Remove Ads / update-Ad-Free (push) Successful in 28s
[Details](https://github.com/UseInterstellar/Interstellar/actions/runs/10783793298/job/29906335526)

pages build and deployment / report-build-status (dynamic) Successful in 9s
[Details](https://github.com/UseInterstellar/Interstellar/actions/runs/10783792118/job/29906340099)

pages build and deployment / deploy (dynamic) Skipped
[Details](https://github.com/UseInterstellar/Interstellar/actions/runs/10783792118/job/29906340170)

Cloudflare Pages - Deployed successfully

**Comment by Kason23** [comment]
help me yo

**Comment by xbubbo** [comment]
There's literally no issue..?
