### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by karmajm** [UseInterstellar/Interstellar#854]
This keeps happening in heroku when I try to use interstellar on it pls help if you can

**Comment by IncognitoTGT** [comment]
what keeps happening?
send the error

**Comment by karmajm** [comment]
![IMG_0368](https://github.com/user-attachments/assets/794dc209-5027-44e0-891d-17240df3180c)

**Comment by karmajm** [comment]
Mb thought I sent it

**Comment by karmajm** [comment]
> what keeps happening? send the error

?

**Comment by karmajm** [comment]
![IMG_0370](https://github.com/user-attachments/assets/431e50a0-0e83-4ee1-aa53-c4a4c4ae2934)
![IMG_0369](https://github.com/user-attachments/assets/1c3ada7a-0a29-4c1b-a781-2dc45aa8b3db)

**Comment by IncognitoTGT** [comment]
delete [package-lock.json](https://github.com/UseInterstellar/Interstellar/blob/main/package-lock.json) from your fork

**Comment by karmajm** [comment]
K

**Comment by karmajm** [comment]
![IMG_0371](https://github.com/user-attachments/assets/39649d48-2eb4-4bb1-8bba-3f3612baa4d5)

**Comment by karmajm** [comment]
Same issue happened still

**Comment by karmajm** [comment]
![Uploading IMG_0373.png…]()

**Comment by karmajm** [comment]
![IMG_0373](https://github.com/user-attachments/assets/db4e3999-2dbb-43f8-a749-9007006acfcd)

**Comment by karmajm** [comment]
Should I delete node.js.index next

**Comment by karmajm** [comment]
> what keeps happening? send the error

![IMG_0374](https://github.com/user-attachments/assets/a12e2d7d-bedc-45f8-afb5-874532f1913f)

**Comment by xbubbo** [comment]
Try deleting all lock files

**Comment by IncognitoTGT** [comment]
stale issue, closing
