### ISSUE TITLE
[BUG] Deeeep.io

### ISSUE THREAD

**Issue by Tmoneytroyt** [UseInterstellar/Interstellar#858]
when i try to go to deeeep.io it and click play it says server error. Its works on other devices but not interstelllar. Im running it on was and using pnpm latest version of interstellar. Nginx Proxy. Anyone else having this issue.
[Screen recording 2024-09-23 8.37.16 AM.webm](https://github.com/user-attachments/assets/f192fc1d-c976-4aaa-ba5a-b9ff3e110bfc)

**Comment by MMMMMMi728y98** [comment]
See issue #825 

Similar problem, solved by JS config file. did you compile your github correctly?

**Comment by IncognitoTGT** [comment]
andrew shin please shut up

**Comment by IncognitoTGT** [comment]
> when i try to go to deeeep.io it and click play it says server error. Its works on other devices but not interstelllar. Im running it on was and using pnpm latest version of interstellar. Nginx Proxy. Anyone else having this issue. [Screen recording 2024-09-23 8.37.16 AM.webm](https://github.com/user-attachments/assets/f192fc1d-c976-4aaa-ba5a-b9ff3e110bfc)

probably a uv issue, which isnt under our control

**Comment by MMMMMMi728y98** [comment]
whoh the fucking hell do  you think you are

**Comment by MMMMMMi728y98** [comment]
> andrew shin please shut up

This is banned from this ig

**Comment by proudparrot2** [comment]
what are you yapping about

**Comment by uhidontkno** [comment]
@MMMMMMi728y98 you have the mental capacity of a rock

**Comment by uhidontkno** [comment]
this mfer is like that one interstellar issue

**Comment by uhidontkno** [comment]
https://github.com/InterstellarNetwork/Interstellar/issues/487#issuecomment-1970200004

**Comment by MMMMMMi728y98** [comment]
This is all bullshit

**Comment by MMMMMMi728y98** [comment]
LIKE YOU SAID THIS IS ALL BULLSHIT...
WORST THING IV HEARD IN MY LIFE

**Comment by MMMMMMi728y98** [comment]
Welp, i tried, but i guess your too stupid to process imformation that quick. I think your fucking bran has gone to hell now

**Comment by uhidontkno** [comment]
> LIKE YOU SAID THIS IS ALL BULLSHIT... WORST THING IV HEARD IN MY LIFE

pov: @MMMMMMi728y98 's mental capacity
https://cdn.discordapp.com/attachments/1194334979929423942/1289651809064980531/watermark.gif?ex=66f99957&is=66f847d7&hm=7459e7958e6540da24e72176bc5b44fba7268ef0045e4ed3c097d5dabf52b85a&

**Comment by MMMMMMi728y98** [comment]
emotional dammit

**Comment by MMMMMMi728y98** [comment]
bitchass

**Comment by uhidontkno** [comment]
> emotional dammit

shush your skiddy ass up before i accidentally make a 1000-word roast about you

**Comment by uhidontkno** [comment]
i already did it

**Comment by MMMMMMi728y98** [comment]
WHat the fuck your ass is not strong enough to hold me. Your the fucking kid here

**Comment by MMMMMMi728y98** [comment]
Besides i think your pc is ass

**Comment by uhidontkno** [comment]
> WHat the fuck your ass is not strong enough to hold me. Your the fucking kid here

guess like you'll learn the hard way

**Comment by MMMMMMi728y98** [comment]
Fuck you

**Comment by MMMMMMi728y98** [comment]
dumass[

**Comment by MMMMMMi728y98** [comment]
@%!$%!!!

**Comment by MMMMMMi728y98** [comment]
https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858https://github.com/UseInterstellar/Interstellar/issues/858

**Comment by MMMMMMi728y98** [comment]
https://github.com/UseInterstellar/Interstellar/issues/858

**Comment by MMMMMMi728y98** [comment]
Wgere is your ass bro oh yeah i forgot i put it in hell womp womp

**Comment by IncognitoTGT** [comment]
can you stop raging, that applies to rare and andrew skid
attack him in #865

**Comment by MMMMMMi728y98** [comment]
what the hell

**Comment by uhidontkno** [comment]
@MMMMMMi728y98 what type of bullshit is your under-developed kindergarten brain spewing out? you sound like me when i was 4 and all i did was spam random shit on the keyboard and yell  in all caps

**Comment by MMMMMMi728y98** [comment]
shit....

**Comment by MMMMMMi728y98** [comment]
stop the fucking deletions

**Comment by IncognitoTGT** [comment]
uv issue, not in our control

**Comment by MMMMMMi728y98** [comment]
what

**Comment by MMMMMMi728y98** [comment]
no

**Comment by MMMMMMi728y98** [comment]
YOU ARE ALL BITCHASSES

**Comment by IncognitoTGT** [comment]
andrew go to #865
