### ISSUE TITLE
[Bug] Interstellar Menu Not Showing in Custom Website

### ISSUE THREAD

**Issue by EdwardDK** [UseInterstellar/Interstellar#861]
**Describe the bug**
I used the Koyeb deploy link in the readme.file
I made a website which incorporate Interstellar in an about:blank.
I ran Interstellar into koyeb and make an about blank through the proccess of making an iframe and setting it full screen.
When I run it through the koyeb link it works: [blushing-chrystal-eddytech-80cafe39.koyeb.app/](https://blushing-chrystal-eddytech-80cafe39.koyeb.app/) but whenever I try to run it through my own custom 
![image](https://github.com/user-attachments/assets/1ddb1f59-f6a4-4b1f-884a-5ec926ab36f1)
it looks like this ^ and I can't search anything and no buttons.

**Expected behavior**
I expected it to work like the normal version, but somehow the about:blank doesn't let it work I suspect.

**Screenshots**
![image](https://github.com/user-attachments/assets/586dff16-ab40-427b-a04d-ff16970b8254)

![image](https://github.com/user-attachments/assets/cea2bb7f-1d0b-4baa-acce-9c79d38f06d1)

**Device Information (please complete the following information):**

- Device: Laptop
- OS Windows
- Browser Chrome

**Additional context**
I used to run the other older version which worked fine, I updated it to this one and now its broken. The issue is not in my Koyeb because it works fine, I also have no way to change the about:blank data so it must be a Interstellar problem.

Thankyou for the help :)

**Comment by xbubbo** [comment]
Are you sure you are on the latest version?? We had this issue a few weeks ago and it was fixed then, it should not still be happening.

**Comment by EdwardDK** [comment]
I'm sorry I don't know because I'm using the koyeb link to deploy off of. What should i do?

**Comment by EdwardDK** [comment]
Can it maybe be because I host it in an about:blank? I tried running it again fresh and same issue.

**Comment by xbubbo** [comment]
![image](https://github.com/user-attachments/assets/f43ea2af-f8da-46d7-81ee-44386e105c15)

**Comment by EdwardDK** [comment]
Yeah i redeploye it on another link [](https://glorious-pamela-eddytech-b67361b5.koyeb.app/)

**Comment by EdwardDK** [comment]
https://glorious-pamela-eddytech-b67361b5.koyeb.app/

**Comment by EdwardDK** [comment]
I think its because of the popout notification. I don't recieve it on my end because of it already running in about:blank

**Comment by EdwardDK** [comment]
Can you tell what script has the popup function? I can fork remove and test it. Thanks

**Comment by EdwardDK** [comment]
https://gentle-shina-eddytech-51d76231.koyeb.app/

**Comment by EdwardDK** [comment]
@xbubbo I fixed it, what i did is a removed a portion of the script in home,js
`if (
  !inFrame &&
  !navigator.userAgent.includes("Firefox") &&
  localStorage.getItem("ab") === "true"
) {
  const popup = open("about:blank", "_blank");
  if (!popup || popup.closed) {
    alert(
      "Please allow popups for this site. Doing so will allow us to open the site in a about:blank tab and preventing this site from showing up in your history. You can turn this off in the site settings.\n\nBy using Interstellar services, you confirm you have read and agreed to the terms listed in our Terms of Service and Privacy Policy, which can be found on the bottom of the settings page.",
    );
  } else {
    const doc = popup.document;
    const iframe = doc.createElement("iframe");
    const style = iframe.style;
    const link = doc.createElement("link");

    const name = localStorage.getItem("name") || "My Drive - Google Drive";
    const icon =
      localStorage.getItem("icon") ||
      "https://ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png";

    doc.title = name;
    link.rel = "icon";
    link.href = icon;

    iframe.src = location.href;
    style.position = "fixed";
    style.top = style.bottom = style.left = style.right = 0;
    style.border = style.outline = "none";
    style.width = style.height = "100%";

    doc.head.appendChild(link);
    doc.body.appendChild(iframe);

    const pLink = localStorage.getItem(encodeURI("pLink")) || getRandomUrl();
    location.replace(pLink);

    const script = doc.createElement("script");
    script.textContent = `
      window.onbeforeunload = function (event) {
        const confirmationMessage = 'Leave Site?';
        (event || window.event).returnValue = confirmationMessage;
        return confirmationMessage;
      };
    `;
    doc.head.appendChild(script);
  }
}`

this script was responsible for the about:blank popout. since I was also running in about:blank it would break the website. It works fine now
