### ISSUE TITLE
andrew shin please shut up

### ISSUE THREAD

**Issue by MMMMMMi728y98** [UseInterstellar/Interstellar#865]
andrew shin please shut up

_Originally posted by @IncognitoTGT in https://github.com/UseInterstellar/Interstellar/issues/858#issuecomment-2381018593_

**Comment by MMMMMMi728y98** [comment]
This should be banned. BAN HIM

**Comment by uhidontkno** [comment]
what

**Comment by proudparrot2** [comment]
> ```
>           andrew shin please shut up
> ```
> 
> _Originally posted by @IncognitoTGT in [#858 (comment)](https://github.com/UseInterstellar/Interstellar/issues/858#issuecomment-2381018593)_

he did in fact say that

**Comment by uhidontkno** [comment]
probably because you're andrew shin

**Comment by uhidontkno** [comment]
retard

**Comment by IncognitoTGT** [comment]
shut your skiddy ass up bro. you literally try to flex to others in school that you can code, but this is the stuff you're writing
![image](https://github.com/user-attachments/assets/74cde644-69ed-4246-b4fa-6158b367fc31)
you're so special you think that scss is a programming language
![Screenshot 2024-09-28 at 19 16 00](https://github.com/user-attachments/assets/7abe7879-1dc9-404e-b842-396d49b2ba22)
god knows what you were thinking when you made this whole mess
![Screenshot 2024-09-28 at 19 16 33](https://github.com/user-attachments/assets/eef4ab4b-2fab-4cb5-9823-08488b4c7a20)
i feel sorry for your friends that thought you can code, while you're just a pathetic skid
![Screenshot 2024-09-28 at 19 17 19](https://github.com/user-attachments/assets/c949e87d-6041-48b2-afc7-6851dce1c3cb)
how high were you?
https://github.com/flutter/flutter/issues?q=+author:as90909w+is:closed

**Comment by uhidontkno** [comment]
@MMMMMMi728y98 reminds me of https://github.com/InterstellarNetwork/Interstellar/issues/487#issuecomment-1970200004

**Comment by IncognitoTGT** [comment]
REAL

**Comment by uhidontkno** [comment]
@MMMMMMi728y98 what type of bullshit is your under-developed kindergarten brain spewing out? you sound like me when i was 4 and all i did was spam random shit on the keyboard and yell  in all caps

**Comment by MMMMMMi728y98** [comment]
oh shit

**Comment by MMMMMMi728y98** [comment]
shut the fuck up right now all you ni 's your all gonna be sad when i throw you at hell

**Comment by IncognitoTGT** [comment]
make me lool

**Comment by MMMMMMi728y98** [comment]
Oh ill make you

**Comment by IncognitoTGT** [comment]
i think you're mad that you can't code

**Comment by IncognitoTGT** [comment]
and that we dispelled your illusion

**Comment by MMMMMMi728y98** [comment]
goddamm you are so stupid

**Comment by uhidontkno** [comment]
> shut the fuck up right now all you ni 's your all gonna be sad when i throw you at hell

![no i dont want to](https://img.rare1k.dev/no-because-i-dont-want-to.gif)

**Comment by MMMMMMi728y98** [comment]
fuck you

**Comment by uhidontkno** [comment]
fuck you too <3

**Comment by IncognitoTGT** [comment]
wimp womp

**Comment by uhidontkno** [comment]
> goddamm you are so stupid

look at your username

**Comment by MMMMMMi728y98** [comment]
dang your all black

**Comment by uhidontkno** [comment]
> dang your all black

you're*

**Comment by MMMMMMi728y98** [comment]
Profanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). The



thats what you are

**Comment by uhidontkno** [comment]
> Profanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). The
> 
> thats what you are

you look like this kid

![image](https://github.com/user-attachments/assets/49a9b4aa-798e-4a59-89aa-00b5723a1de4)

**Comment by MMMMMMi728y98** [comment]
shut the hell up rgh now or ill fuck all you asses to my fucking ####################### you ni#####

**Comment by IncognitoTGT** [comment]
how am i the definition of a word
you're the reason your school can't have nice things--there's a knowledge barrier between you and the rest of the students

> Profanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). The
> 
> thats what you are

**Comment by MMMMMMi728y98** [comment]
nope

**Comment by MMMMMMi728y98** [comment]
damn bro thats tough your all bitchasses even 3kh0

**Comment by uhidontkno** [comment]
> nope

you're the reason why my school dropped afternoon detention

**Comment by MMMMMMi728y98** [comment]
mabye you got detention because you pretend to be smart but instead, youProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). TheProfanity may be described as offensive language, dirty words, or taboo words, among other descriptors. The term [profane](https://en.wiktionary.org/wiki/profane) originates from classical [Latin](https://www.bing.com/search?q=Latin%20wikipedia&form=WIKIRE) [profanus](https://en.wiktionary.org/wiki/profanus), literally 'before (outside) the temple', pro meaning 'outside' and fanum meaning 'temple, sanctuary'. This further developed in [Middle English](https://www.bing.com/search?q=Middle%20English%20wikipedia&form=WIKIRE) with the meaning to desecrate a temple. In English, swearing is a catch-all linguistic term for the use of profanities, even if it does not involve taking an [oath](https://www.bing.com/search?q=Oath%20wikipedia&form=WIKIRE). The

**Comment by IncognitoTGT** [comment]
are you just gonna spam that
are you coping
did you run out of responses

**Comment by MMMMMMi728y98** [comment]
You nige

**Comment by uhidontkno** [comment]
cope harder my guy

**Comment by MMMMMMi728y98** [comment]
fuck t

**Comment by uhidontkno** [comment]
im gonna put this gh issue over minecraft stal

**Comment by MMMMMMi728y98** [comment]
oh shit

**Comment by MMMMMMi728y98** [comment]
i am enjoying this conversation, because all your comments are making you look dumb

**Comment by IncognitoTGT** [comment]
> i am enjoying this conversation, because all your comments are making you look dumb

seems like you have a language barrier

**Comment by uhidontkno** [comment]
> i am enjoying this conversation, because all your comments are making you look dumb

yea me too you're the dumbest

**Comment by uhidontkno** [comment]
andrew shein

**Comment by MMMMMMi728y98** [comment]
fucking

**Comment by uhidontkno** [comment]
![image](https://github.com/user-attachments/assets/49eb608a-de35-448e-80f6-1656e42081c0)

**Comment by MMMMMMi728y98** [comment]
ni

**Comment by MMMMMMi728y98** [comment]
ge

**Comment by IncognitoTGT** [comment]
rage harder bro

**Comment by MMMMMMi728y98** [comment]
rs

**Comment by ka-studios** [comment]
copium

**Comment by uhidontkno** [comment]
i found retardium chat in 100% pure form

**Comment by MMMMMMi728y98** [comment]
You all made this happen
![Screenshot 2024-09-28 4 40 11 PM](https://github.com/user-attachments/assets/17d1590e-ca75-46d7-bd8e-3cf263c423e9)

**Comment by uhidontkno** [comment]
> i found retardium chat in 100% pure form

![image](https://github.com/user-attachments/assets/a94d7359-dc26-4a0b-a08f-67633bfc342c)

**Comment by MMMMMMi728y98** [comment]
Wow your a dangerougs gun men oh no kill him

**Comment by IncognitoTGT** [comment]
> You all made this happen ![Screenshot 2024-09-28 4 40 11 PM](https://private-user-images.githubusercontent.com/182548379/371812465-17d1590e-ca75-46d7-bd8e-3cf263c423e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NjcxODcsIm5iZiI6MTcyNzU2Njg4NywicGF0aCI6Ii8xODI1NDgzNzkvMzcxODEyNDY1LTE3ZDE1OTBlLWNhNzUtNDZkNy1iZDhlLTNjZjI2M2M0MjNlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQyMzQxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODg1MWM0NmY3NWUxZGIwNGVkZDllMTQ0NTE0MmY0YTc2MjgwMWQyODkxZTFkZGMxYWUyOTdmYzAwODljZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._dFUqmoez-4wJ3Cd0u61Bnth6iBk9Os0vDApljkwPqo)

this kid seriously leaked his school

**Comment by ka-studios** [comment]
this dumbfuck :skull:

**Comment by MMMMMMi728y98** [comment]
how old even are ya

**Comment by MMMMMMi728y98** [comment]
27?

**Comment by ka-studios** [comment]
old enough

**Comment by ka-studios** [comment]
and youre like what

**Comment by ka-studios** [comment]
12?

**Comment by MMMMMMi728y98** [comment]
old enough so that your fucking brain dosent work like that

**Comment by MMMMMMi728y98** [comment]
14

**Comment by uhidontkno** [comment]
> 14

you act like you're 7

**Comment by uhidontkno** [comment]
or 5

**Comment by MMMMMMi728y98** [comment]
mabye its because your brain is stupid

**Comment by IncognitoTGT** [comment]
> 14

how much did you get held back

**Comment by uhidontkno** [comment]
ngl you seem like one of those kids that don't do any of their work and casually get a 38% in all of their core classes

**Comment by IncognitoTGT** [comment]
you cant even code sh

**Comment by ka-studios** [comment]
pov:
![image](https://github.com/user-attachments/assets/7fd72069-0555-4d0f-ba13-cb0107bce09e)

**Comment by MMMMMMi728y98** [comment]
oh im a straight a student meanwhile...your a staight -F student

**Comment by ka-studios** [comment]
youre just spamming every single library

**Comment by IncognitoTGT** [comment]
clearly not

**Comment by MMMMMMi728y98** [comment]
hm you seem like a nigering child here

**Comment by ka-studios** [comment]
"Window 11"
"Mac X"
"Beta coder"

**Comment by ka-studios** [comment]
uses 909384091834 differnet languages and uses bazel and gradle to build

**Comment by ka-studios** [comment]
gradle does NOT build javaSCRIPT :facepalm:

**Comment by ka-studios** [comment]
what in the actual fuck is this
![image](https://github.com/user-attachments/assets/82d8fca3-6de8-4a96-8370-60dbf034987b)

**Comment by IncognitoTGT** [comment]
> oh im a straight a student meanwhile...your a staight -F student

*F-

**Comment by MMMMMMi728y98** [comment]
why do you care

**Comment by MMMMMMi728y98** [comment]
ohhhhh i get it your too dumb so you cant code! get outta here

**Comment by ka-studios** [comment]
"coding for development"

**Comment by ka-studios** [comment]
buddy its clear asf that you have a "-F" in your english class

**Comment by MMMMMMi728y98** [comment]
I SAid get the hell outta here

**Comment by IncognitoTGT** [comment]
> uses 909384091834 differnet languages and uses bazel and gradle to build

dude he just copies random lines of code into files with those extensions so that he can flex the rainbow

**Comment by MMMMMMi728y98** [comment]
your a niger

**Comment by IncognitoTGT** [comment]
> I SAid get the hell outta here

make us

**Comment by MMMMMMi728y98** [comment]
niger

**Comment by MMMMMMi728y98** [comment]
never back down fuck the child

**Comment by IncognitoTGT** [comment]
what does a country have to do with me getting out allegedly

**Comment by ka-studios** [comment]
package-lock.json but no package.json is wild

**Comment by IncognitoTGT** [comment]
it would be a shame if i emailed your school about your online conduct

**Comment by ka-studios** [comment]
![image](https://github.com/user-attachments/assets/0b43104b-2fa0-4988-b0c4-4a7b97e337b7)

**Comment by MMMMMMi728y98** [comment]
You dont know my schools email

**Comment by IncognitoTGT** [comment]
> You dont know my schools email

you just sent your school

**Comment by ka-studios** [comment]
> You dont know my schools email

the internet exists

**Comment by MMMMMMi728y98** [comment]
why are you in vs

**Comment by IncognitoTGT** [comment]
and i know your full name

**Comment by MMMMMMi728y98** [comment]
damn yall are weak bro

**Comment by IncognitoTGT** [comment]
andrew tell us your discord

**Comment by ka-studios** [comment]
https://base.beaverton.k12.or.us/connect/contact-us/hs2-contact-us-form

**Comment by IncognitoTGT** [comment]
> https://base.beaverton.k12.or.us/connect/contact-us/hs2-contact-us-form

scroll up he sent his actual high school

**Comment by MMMMMMi728y98** [comment]
no if i did tell you y discord, you would keep spamming me messages

**Comment by IncognitoTGT** [comment]
> no if i did tell you y discord, you would keep spamming me messages

scaredy cat

**Comment by MMMMMMi728y98** [comment]
nah bro is actully trying to crash out

**Comment by IncognitoTGT** [comment]
says the one cosntantly spamming insults

**Comment by MMMMMMi728y98** [comment]
if you call me a nigering child 100 times imma crash out on my pc
![Screenshot 2024-09-28 4 54 12 PM](https://github.com/user-attachments/assets/3958bf18-a215-4afa-a682-9a9897eb3b5c)

**Comment by IncognitoTGT** [comment]
do it

**Comment by MMMMMMi728y98** [comment]
fuckersssssss

**Comment by uhidontkno** [comment]
> > no if i did tell you y discord, you would keep spamming me messages
> 
> scaredy cat

pussy

**Comment by IncognitoTGT** [comment]
![Screenshot 2024-09-28 at 19 55 47](https://github.com/user-attachments/assets/81f3b680-bf1c-4ac9-bb0e-901a72aec2e7)
fake ahh pic

**Comment by MMMMMMi728y98** [comment]
Why did you make this dumb repository anyway

**Comment by uhidontkno** [comment]
he didnt?

**Comment by MMMMMMi728y98** [comment]
Ik that you think im gonna show my real pc?

**Comment by uhidontkno** [comment]
smartass

**Comment by uhidontkno** [comment]
you have the biggest ego ive ever seen

**Comment by MMMMMMi728y98** [comment]
Do ya? your just gonna search it up then your gonna like ban it

**Comment by IncognitoTGT** [comment]
> Do ya? your just gonna search it up then your gonna like ban it

how would we ban it

**Comment by MMMMMMi728y98** [comment]
Emailing

**Comment by IncognitoTGT** [comment]
we already emailed your school

**Comment by MMMMMMi728y98** [comment]
uh huh

**Comment by IncognitoTGT** [comment]
> Emailing

how would we get your computer banned for that isnt it your personal setup

**Comment by uhidontkno** [comment]
> why is this not locked

its so stupid its funny

**Comment by uhidontkno** [comment]
this kid reminds me of #487

**Comment by uhidontkno** [comment]
https://github.com/InterstellarNetwork/Interstellar/issues/487#issuecomment-1970200004

**Comment by Piplup7575** [comment]
you want to "collaborate on 3kh0"? nah i think we're good

**Comment by IncognitoTGT** [comment]
thats widl

**Comment by uhidontkno** [comment]
andrew shein

**Comment by Piplup7575** [comment]
> > you want to "collaborate on 3kh0"? nah i think we're good
> 
> cook 3kh0 on a grill then we can collaborate eating them (andrew shin is great at this)

@3kh0 can i grill you please it'd be fun

**Comment by IncognitoTGT** [comment]
yeah let the skid have his meal
they can't just have cake

**Comment by uhidontkno** [comment]
> yeah let the skid have his meal they can't just have cake

this is the perfect comment to lock this issue on

**Comment by IncognitoTGT** [comment]
anyways im gonna lock this since the skid shut up
