### ISSUE TITLE
I have no idea what to do when this happens: RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

### ISSUE THREAD

**Issue by GigaChad12345-code** [UseInterstellar/Interstellar#866]
I try to type in a website and it just pops up and says that it has an error, please help

**To Reproduce**

1. Go to Interstellar
2. Click on search bar
3. Type in anything

I expected to be directed to the site I was searching

**Device Information (please complete the following information):**

- Device: Chromebook
- OS: ChromeOS
- Browser: Chrome

**Comment by williamn-bit** [comment]
I have the same problem

**Comment by IncognitoTGT** [comment]
did you make your codespace public?

**Comment by GigaChad12345-code** [comment]
> did you make your codespace public?

yes, I did: https://github.com/GigaChad12345-code/Gigachad-Proxy

**Comment by yq4qs** [comment]
does this for me too and I cant find a solution
