### ISSUE TITLE
GeForce Now not working

### ISSUE THREAD

**Issue by HeHe-Bot196** [UseInterstellar/Interstellar#892]
Whenever I open GeForce Now whether I am on my home or school internet on interstellar. It always gets me to the front of the queue and the loads to about 75 percent and says that it has a problem connecting.

**Comment by hi696969** [comment]
skill issues

**Comment by HeHe-Bot196** [comment]
gay
________________________________

**Comment by hi696969** [comment]
says u what u mean

**Comment by replitidk** [comment]
try with a new codespace
