### ISSUE TITLE
[Bug] RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

### ISSUE THREAD

**Issue by Bugydigital** [UseInterstellar/Interstellar#900]
Basically when I'm searching for something or trying to go to a site, I get this error:
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

I'm using a school chromebook for this btw

idk what else to put

**Comment by IncognitoTGT** [comment]
make your codespace public

**Comment by 77777777777778** [comment]
IncognitoTGT

**Comment by hi696969** [comment]
after you do npm i and npm run start you will see it to do in your
browser or make it public you need to make it public

**Comment by 77777777777778** [comment]
bet
