### ISSUE TITLE
[Feature] Let server admins add custom websites from config.js

### ISSUE THREAD

**Issue by debug-cli** [UseInterstellar/Interstellar#933]
When i make a Custom Website on the Interstellar Proxy games page, i am hosting it for multiple people on my server and it dosen't just not save it on the proxy's game page forever, but it also dosen't show it for other people on their computers.

I want there to be a option in config.js to add custom websites in the games or apps page (both)

For example, with the current structure of the config.js file it would look like this.

```
const config = {
  challenge: true, // Set to true if you want to enable password protection.
  blocked: {
    // Normal users can ignore this option. This is for the owner of the website.
    "gointerstellar.app": "",
  },
  users: {
    // You can add multiple users by doing username: 'password'.
  },
  custom_websites: {
    // You can add custom websites by doing name: 'URL'.
    example website: 'example.com'
  },
};

export default config;
```

***Additional Feature Requests***
Add the add custom website button to the apps tab too please.

***Additional Context***
- I got this idea from the current feature in the game tab that lets you add custom websites as games.
- It gives server admins more control and if users want more games the server admin can add it easily and not have to make a game request on GitHub.
- config.js needs at least 1 update. it's been a while

**Comment by Aymano200** [comment]
You already add games via the [g.json file](static/assets/json/g.json), read [Contributing.md](/contributing.md) to find how to do so
