### ISSUE TITLE
[Bug] Roblox still doesn't work.

### ISSUE THREAD

**Issue by AnshOS** [UseInterstellar/Interstellar#941]
**It doesn't work**
It still says it is a proxy detected.

Please fix soon.

**Comment by maxwick456** [comment]
It works on Max's Games!
# All maxgames links
[maxgames.pages.dev](https://maxgames.pages.dev/)
[99v.org](https://99v.org/)
[maxj.me](https://maxj.me/)
[max.alderteam.com](https://max.alderteam.com/)
[games.alderteam.com](https://games.alderteam.com/)
[maxgames.alderteam.com](https://maxgames.alderteam.com/)
[max.wr.do](https://max.wr.do/)
[ubg.wr.do](https://ubg.wr.do/)
[games.wr.do](https://games.wr.do/)
You are welcome

**Comment by AnshOS** [comment]
Oh then I think it is wherever you host it because I host Koyeb in Germany and it says that it doesn’t support this region.
